version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "timestreamReaderUDQ"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-lu5f49oyq27x"
s3_prefix = "timestreamReaderUDQ"
region = "ap-northeast-1"
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
