version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "timestreamReaderUDQ"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-51udi5jy0ap9"
s3_prefix = "timestreamReaderUDQ"
region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
