AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  timestreamReaderUDQ

Globals:
  Function:
    Timeout: 900
    MemorySize: 256
    Tracing: Active


Resources:

  TimestreamUdqRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: 'TimestreamUdqRole'
      AssumeRolePolicyDocument:
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
        - 'arn:aws:iam::aws:policy/AmazonTimestreamReadOnlyAccess'

  UdqHelperUtilsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Layer for util
      ContentUri: 'udq_helper_utils/'
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9

  UdqDataReaderFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt TimestreamUdqRole.Arn
      CodeUri: udq_data_reader/
      Handler: udq_data_reader.lambda_handler
      Runtime: python3.9
      Layers:
        - !Ref UdqHelperUtilsLayer
      Architectures:
      - x86_64
      Environment:
        Variables:
          TIMESTREAM_DATABASE_NAME: 'IoTButtonEventDB'
          TIMESTREAM_TABLE_NAME: 'IoTButtonEventTable'

  UdqDataReaderFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${UdqDataReaderFunction}
      RetentionInDays: 1