AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  timestreamReaderUDQ

Globals:
  Function:
    Timeout: 300
    # MemorySize: 128
    Tracing: Active


Resources:
  UdqHelperUtilsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Layer for util
      ContentUri: 'udq_helper_utils/'
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9

  UdqDataReaderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: udq_data_reader/
      Handler: udq_data_reader.lambda_handler
      Runtime: python3.9
      Layers:
        - !Ref UdqHelperUtilsLayer
      Architectures:
      - x86_64
      Environment:
        Variables:
          TIMESTREAM_DATABASE_NAME: 'IoTButtonEventDB'
          TIMESTREAM_TABLE_NAME: 'IoTButtonEventTable'